fix(config): 🧩fallback config for `serializationisbad`
Currently `SerializationIsBad` will download latest configs, which works fine in most cases.
But if the internet connection is bad, and no pre-made configs for SerializationIsBad, a hard crash will happen:
```
RuntimeException: You are currently using SerializationIsBad without any patch modules configured.
```

We provide a pre-made config for SerializationIsBad, so that when the internet is down, the game can still launch using provided fallback config.

Fix https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/269